# Generated by Django 6.0 on 2026-01-05 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('parameters', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Swing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('timeframe', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('high', 'High'), ('low', 'Low')], max_length=10)),
                ('price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('timestamp', models.DateTimeField()),
                ('retracement_level', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_valid', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('timeframe', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('low_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('close_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'ordering': ['timestamp'],
                'unique_together': {('symbol', 'timeframe', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='Correlation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair1', models.CharField(max_length=10)),
                ('pair2', models.CharField(max_length=10)),
                ('correlation_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('timestamp', models.DateTimeField()),
                ('timeframe', models.CharField(max_length=10)),
            ],
            options={
                'unique_together': {('pair1', 'pair2', 'timestamp', 'timeframe')},
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('timeframe', models.CharField(max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('direction', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('outcome', models.CharField(choices=[('WIN', 'Win'), ('LOSS', 'Loss'), ('OPEN', 'Open')], default='OPEN', max_length=10)),
                ('correlation_checked', models.BooleanField(default=False)),
                ('correlation_valid', models.BooleanField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('entry_candle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_trades', to='trading.candle')),
                ('exit_candle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exit_trades', to='trading.candle')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.strategy')),
            ],
            options={
                'ordering': ['entry_candle__timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('value', models.DecimalField(decimal_places=5, max_digits=10)),
                ('slope', models.DecimalField(decimal_places=5, max_digits=10)),
                ('candle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.candle')),
            ],
            options={
                'unique_together': {('candle', 'type')},
            },
        ),
    ]
