# Generated by Django 6.0 on 2026-01-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='ml_probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='risk_r',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='stop_loss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='take_profit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candle',
            name='close_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='candle',
            name='high_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='candle',
            name='low_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='candle',
            name='open_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='candle',
            name='volume',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='correlation',
            name='correlation_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='slope',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='swing',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='entry_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='exit_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='pnl',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
